[build]
  command = "npm run build"
  publish = "dist"

# Ensure SPA fallback works for all paths
[[redirects]]
  from = "/es"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ru"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
